### ISSUE TITLE
Send `failure_expanded` on Jest failures

### ISSUE THREAD

**Issue by toolmantim** [buildkite/test-collector-javascript#17]

**Comment by nprizal** [comment]
@mariovisic `failureMessage` is the summary of **all** failed tests for a specific test file. Fo **individual** test, the information we can use is either `failureMessages` or `failureDetails` (see below)

`testResult` object passed by `onTestResult`:
```
{
  leaks: false,
  numFailingTests: 2,
  numPassingTests: 1,
  numPendingTests: 0,
  numTodoTests: 0,
  openHandles: [
  ],
  perfStats: {
    end: 1674512775983,
    runtime: 119,
    slow: false,
    start: 1674512775864,
  },
  skipped: false,
  snapshot: {
    added: 0,
    fileDeleted: false,
    matched: 0,
    unchecked: 0,
    uncheckedKeys: [
    ],
    unmatched: 0,
    updated: 0,
  },
  testFilePath: "/Users/naufanrizal/Repositories/test-collector-javascript/examples/jest/example.test.js",
  testResults: [
    {
      ancestorTitles: [
      ],
      duration: 1,
      failureDetails: [
      ],
      failureMessages: [
      ],
      fullName: "1 + 2 to equal 3",
      invocations: 1,
      location: {
        column: 1,
        line: 2,
      },
      numPassingAsserts: 0,
      retryReasons: [
      ],
      status: "passed",
      title: "1 + 2 to equal 3",
    },
    {
      ancestorTitles: [
      ],
      duration: 1,
      failureDetails: [
        {
          matcherResult: {
            actual: 2,
            expected: 3,
            message: "expect(received).toBe(expected) // Object.is equality\n\nExpected: 3\nReceived: 2",
            name: "toBe",
            pass: false,
          },
        },
      ],
      failureMessages: [
        "Error: expect(received).toBe(expected) // Object.is equality\n\nExpected: 3\nReceived: 2\n    at Object.toBe (/Users/naufanrizal/Repositories/test-collector-javascript/examples/jest/example.test.js:7:17)\n    at Promise.then.completed (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/utils.js:333:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/utils.js:259:10)\n    at _callCircusTest (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:276:40)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at _runTest (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:208:3)\n    at _runTestsForDescribeBlock (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:96:9)\n    at run (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:31:3)\n    at runAndTransformResultsToJestFormat (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)",
      ],
      fullName: "1 + 1 equal 3",
      invocations: 1,
      location: {
        column: 1,
        line: 6,
      },
      numPassingAsserts: 0,
      retryReasons: [
      ],
      status: "failed",
      title: "1 + 1 equal 3",
    },
    {
      ancestorTitles: [
        "sum",
      ],
      duration: 0,
      failureDetails: [
        {
          matcherResult: {
            actual: 41,
            expected: 42,
            message: "expect(received).toBe(expected) // Object.is equality\n\nExpected: 42\nReceived: 41",
            name: "toBe",
            pass: false,
          },
        },
      ],
      failureMessages: [
        "Error: expect(received).toBe(expected) // Object.is equality\n\nExpected: 42\nReceived: 41\n    at Object.toBe (/Users/naufanrizal/Repositories/test-collector-javascript/examples/jest/example.test.js:13:20)\n    at Promise.then.completed (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/utils.js:333:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/utils.js:259:10)\n    at _callCircusTest (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:276:40)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at _runTest (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:208:3)\n    at _runTestsForDescribeBlock (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:96:9)\n    at _runTestsForDescribeBlock (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:90:9)\n    at run (/Users/naufanrizal/Repositories/test-collector-javascript/node_modules/jest-circus/build/run.js:31:3)",
      ],
      fullName: "sum 40 + 1 equal 42",
      invocations: 1,
      location: {
        column: 3,
        line: 12,
      },
      numPassingAsserts: 0,
      retryReasons: [
      ],
      status: "failed",
      title: "40 + 1 equal 42",
    },
  ],
  console: undefined,
  displayName: undefined,
  failureMessage: "  ● 1 + 1 equal 3\n\n    expect(received).toBe(expected) // Object.is equality\n\n    Expected: 3\n    Received: 2\n\n       5 |\n       6 | test('1 + 1 equal 3', () => {\n    >  7 |   expect(1 + 1).toBe(3);\n         |                 ^\n       8 | })\n       9 |\n      10 | // In a scope\n\n      at Object.toBe (example.test.js:7:17)\n\n  ● sum › 40 + 1 equal 42\n\n    expect(received).toBe(expected) // Object.is equality\n\n    Expected: 42\n    Received: 41\n\n      11 | describe('sum', () => {\n      12 |   test('40 + 1 equal 42', () => {\n    > 13 |     expect(40 + 1).toBe(42);\n         |                    ^\n      14 |   });\n      15 | })\n      16 |\n\n      at Object.toBe (example.test.js:13:20)\n",
  testExecError: undefined,
}
```

We can send the first line of individual test's `failureMessages` as `failureReason` and the rest of the lines as `failureExpanded`.
